apiVersion: v1
kind: Service
metadata:
  name: talentsphere-test-redis
  namespace: talentsphere-test
spec:
  type: ClusterIP
  selector:
    app: talentsphere-test-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: talentsphere-test-redis
  namespace: talentsphere-test
spec:
  serviceName: talentsphere-test-redis
  replicas: 1
  selector:
    matchLabels:
      app: talentsphere-test-redis
  template:
    metadata:
      labels:
        app: talentsphere-test-redis
    spec:
      nodeSelector:
        kubernetes.azure.com/agentpool: agentpool
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379
              name: redis
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: REDIS_PASSWORD
          args:
            - sh
            - -c
            - |
              exec redis-server \
                --appendonly yes \
                --requirepass "$REDIS_PASSWORD"
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "2Gi"
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
